### ISSUE TITLE
Delete console.log

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/CryptoReportss#26]
[Don't leave console logs in production](https://dev.to/mornir/-dont-leave-console-logs-in-production-14na)

**Comment by msachi** [comment]
The same goes for commented-out code!

**Comment by tawfiknasser** [comment]
https://github.com/facn5/CryptoReports/blob/97e33d21578ebad94196f24d2e333652af567d96/scripts/news.js#L49-L57
