### ISSUE TITLE
Design suggestion for the articles  

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/CryptoReportss#33]
**Design suggestion for the articles**  in the mobile view : 
i suggest to have one article each row in place of two articles in one row.
it makes it more readable 
![0000000000](https://user-images.githubusercontent.com/36166288/54282304-63090780-45a4-11e9-8d15-88bff53c9109.png)

**Comment by ghost** [comment]
Done, please review

**Comment by tawfiknasser** [comment]
Nice Work :smile:
