### ISSUE TITLE
duplicated code in JS

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/CryptoReportss#35]
https://github.com/facn5/CryptoReports/blob/63151bcf5a1eca7fa2f6106620a7d2cbb80c1253/scripts/geolocate.js#L4-L14

with 

https://github.com/facn5/CryptoReports/blob/63151bcf5a1eca7fa2f6106620a7d2cbb80c1253/scripts/geolocate.js#L16-L26

can be abstracted in one fetch
also : 
https://github.com/facn5/CryptoReports/blob/63151bcf5a1eca7fa2f6106620a7d2cbb80c1253/scripts/crypt.js#L26-L39
with
https://github.com/facn5/CryptoReports/blob/63151bcf5a1eca7fa2f6106620a7d2cbb80c1253/scripts/crypt.js#L51-L64

**Comment by ghost** [comment]
Done, please review

**Comment by tawfiknasser** [comment]
Any commit reference that i can review ?
